name: Build and Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        rv: ["1.56.0", "stable", "nightly"]

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rv }}
        override: true
        components: rustfmt, clippy
    - run: rustc --version
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
